In [1]:
import sys

sys.path.append("../")
sys.path.append("../../")

from difference_matrix import Difference_Matrix

import numpy as np

from prior_models import normal_prior

### General Performance tests for matrix inversion algorithms

Let's create a second order difference matrix

In [2]:
D=Difference_Matrix(n=100,k=1)

In [3]:
D.D

array([[ 1., -2.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1., -2., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ..., -2.,  1.,  0.],
       [ 0.,  0.,  0., ...,  1., -2.,  1.]])

In [4]:
D.compute_k_difference(0)

array([[-1.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0., -1.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0., -1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ..., -1.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0., -1.,  1.]])

In [5]:
D.D.shape

(98, 100)

In [6]:
(D.DDT.dot(D.DDT_inv)-np.eye(100-2)).max()

7.275957614183426e-12

### Confirm DDT inverse computed correctly via LAPACK

In [7]:
assert(np.allclose(D.DDT.dot(D.DDT_inv),np.eye(100-2),rtol=10e-8,atol=10e-8))

In [8]:
D=Difference_Matrix(100,2)

In [9]:
assert(np.allclose(D.DDT.dot(D.DDT_inv),np.eye(100-3),rtol=10e-4,atol=10e-4))

### Large computations of Difference Matrix


In [10]:
D=Difference_Matrix(1000,1)

In [11]:
assert(np.allclose(D.DDT.dot(D.DDT_inv),np.eye(1000-2),rtol=1e-2,atol=1e-2))

In [12]:
D=Difference_Matrix(1000,1)


In [13]:
assert(np.allclose(D.DDT.dot(D.DDT_inv),np.eye(1000-2),rtol=1e-2,atol=1e-2))

### High order difference matrix

In [14]:
D=Difference_Matrix(100,3)
D.D

array([[ 1., -4.,  6., ...,  0.,  0.,  0.],
       [ 0.,  1., -4., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ..., -4.,  1.,  0.],
       [ 0.,  0.,  0., ...,  6., -4.,  1.]])

In [15]:
((D.DDT.dot(D.DDT_inv))-np.eye(100-4)).max()


3.46451997756958e-07

### Confirm Difference Matrix Recursion works

In [16]:
D=Difference_Matrix(2500,1)
d_21=D.compute_k_difference(21)
d_21

array([[  1., -22., 231., ...,   0.,   0.,   0.],
       [  0.,   1., -22., ...,   0.,   0.,   0.],
       [  0.,   0.,   1., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   1.,   0.,   0.],
       [  0.,   0.,   0., ..., -22.,   1.,   0.],
       [  0.,   0.,   0., ..., 231., -22.,   1.]])

In [17]:
D=Difference_Matrix(2500,21)


AssertionError: 

In [ ]:
assert (np.allclose(d_21,D.D))

### Time Difference Matrix Computation

In [18]:
D=Difference_Matrix(100,1)

T=Difference_Matrix(100,k=1,t=np.linspace(0,1,100))

In [19]:
assert(np.allclose(T.DDT.dot(T.DDT_inv),np.eye(100-2),rtol=1e-8,atol=1e-8))

In [20]:
D=Difference_Matrix(100,1)

T=Difference_Matrix(100,k=1,t=np.linspace(0,1,100))

In [21]:
assert(np.allclose(T.DDT.dot(T.DDT_inv),np.eye(100-2),rtol=1e-8,atol=1e-8))

### Edge Cases

In [22]:
D=Difference_Matrix(100,0)

assert(np.allclose(D.DDT.dot(D.DDT_inv),np.eye(100-1),rtol=1e-8,atol=1e-8))

In [23]:
T=Difference_Matrix(100,k=0,t=np.linspace(0,1,100))

In [24]:
D=Difference_Matrix(100,0)
D.D

array([[-1.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0., -1.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0., -1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ..., -1.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0., -1.,  1.]])

In [25]:
truncated_D=Difference_Matrix(99,0)
truncated_D.D


array([[-1.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0., -1.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0., -1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ..., -1.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0., -1.,  1.]])

In [26]:
truncated_D.D.dot(D.D)

array([[ 1., -2.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1., -2., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ..., -2.,  1.,  0.],
       [ 0.,  0.,  0., ...,  1., -2.,  1.]])

### Testing the performance of Prior Weighted Matrices

In [27]:
prior=normal_prior.Normal_Prior(100,1,1)
prior.prior

array([ 0.1487318 ,  1.38450854,  1.45913282,  0.58447002,  1.56399693,
        1.78621766, -0.05913513,  0.19650203,  1.18206805,  1.54463676,
        2.33844479,  1.30580755, -0.05640482,  0.11668889,  1.65045638,
        2.59446365,  1.75743233,  1.74926773,  0.75243046, -0.98392387,
        0.05507908,  0.74926586,  0.40344766,  1.11170571,  1.00126487,
        0.84523799,  2.00845137,  1.63451627,  2.40210836,  1.05117117,
        1.00463434, -0.04555228,  0.53070182,  2.04722233,  0.91115794,
        1.88982296,  1.92539998,  2.29243643,  1.19362446,  0.73590867,
        1.23420413,  2.6212728 ,  2.75587389, -0.17951225,  0.84882177,
        0.46141464,  1.70904239,  1.51411197,  0.00613605,  1.6072603 ,
        1.73554605,  1.99425808,  2.07122609,  1.30290706,  1.91720738,
       -0.35331123,  0.25381397,  1.73557109,  2.01106739,  0.95852398,
        1.75726124, -0.03087014,  1.06920767,  1.9305044 , -0.26446251,
       -0.15922336,  1.9223364 ,  0.27971275,  0.14555489,  1.58

In [28]:
P=Difference_Matrix(100,1,prior=prior.prior)
P.D

AssertionError: 

In [ ]:
assert(np.allclose(P.DDT.dot(P.DDT_inv),np.eye(100-2),rtol=1e-8,atol=1e-8))

In [ ]:
(P.DDT.dot(P.DDT_inv)-np.eye(100-2)).max()

3.7345163993405706e-10